version: '3.8'

services:  
  webscraper:
    build: .
    container_name: huurhuis-webscraper    
    volumes:
      - ./logs:/app/logs
      - /opt/secrets/webscraper_config.py:/app/webscraper_config.py:ro
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: huurhuis-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=HuurhuizenWebscraper
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
